### ISSUE TITLE
Norm in calculating accuracy

### ISSUE THREAD

**Issue by fleinen** [yuanyuanli85/Stacked_Hourglass_Network_Keras#16]
Hi,

thank you for sharing your work.
I have a question regarding the calculation of the accuracy:
[Here](https://github.com/yuanyuanli85/Stacked_Hourglass_Network_Keras/blob/eddf0ae15715a88d7859847cfff5f5092b260ae1/src/eval/eval_heatmap.py#L20) you use a norm and threshold to calculate if a keypoint was predicted successfully. What is the use of the norm parameter? Mathematically, both values could be easily summarized to just a single value.

Best
Fabian

**Comment by yuanyuanli85** [comment]
This parameter is used to normalize the distance with different resolution.  For example, the prediction is treated as incorrect if the distance < 4 in a [64, 64] heatmap.  but, that distance is okay if the resolution heatmap is [128, 128].

**Comment by fleinen** [comment]
Thank you!
