### ISSUE TITLE
[Question] Was there a reason to keep track of metrics=['accuracy'] when building the model?

### ISSUE THREAD

**Issue by chojuahn** [yuanyuanli85/Stacked_Hourglass_Network_Keras#28]
I'm just trying to understand if I can remove it. I don't see a point of keeping it in regression problem.

**Comment by yuanyuanli85** [comment]
yes, you can remove accuracy metric. It is just an indicator.  Key point detection is not a typical regression problem, it predictes the heat map instead of the loacation of key point.
