### ISSUE TITLE
Cannot download pretrained model

### ISSUE THREAD

**Issue by chnanc001** [yuanyuanli85/Stacked_Hourglass_Network_Keras#5]
I cannot open the links to the pre-trained models, is it possible to load them onto a google drive?

**Comment by yuanyuanli85** [comment]
I have uploaded them to Google drive and update the links in Readme.  Please check latest commit 640177e

**Comment by chnanc001** [comment]
thank you!

When I run the quick demo.py on the sample images I get the error "ImportError: No module named tensorflow," however, I have installed tensorflow using: 
pip install tensorflow 

is this not sufficient?

**Comment by yuanyuanli85** [comment]
I have no idea why python does not find tensorflow. I think you can find answers from google. 

I will close this issue since it has been solved.

**Comment by chnanc001** [comment]
fixed it by running it from an IDE instead of cmd
