### ISSUE TITLE
Just train the face point

### ISSUE THREAD

**Issue by jackweiwang** [yuanyuanli85/Stacked_Hourglass_Network_Keras#9]
How can i change it?

thank you.

**Comment by jackweiwang** [comment]
I want train 98 point in face landmark，but i don't know how to make dataset label. Have you done that before?

**Comment by yuanyuanli85** [comment]
No. have not done that before.

**Comment by jackweiwang** [comment]
I see， thank you

**Comment by jackweiwang** [comment]
Hi @yuanyuanli85  
Excuse me, i have a problem
`np.array([ 0.4404, 0.4440, 0.4327])` 
How do you evaluate this mean value?

**Comment by yuanyuanli85** [comment]
The mean value comes from the mpii training dataset.
